/**
 * Component Generator - Generates Component() constructor code
 *
 * Wraps Vue3 Composition API code into mini-program Component constructor
 * with proper data, methods, properties, and lifecycle handling.
 */

export interface ComponentGeneratorOptions {
  /** Component name */
  name: string;
  /** Compiled script code */
  scriptCode: string;
  /** Reactive variables (from ref/reactive) */
  reactiveVars: string[];
  /** Template dependencies */
  templateDeps: string[];
  /** Props definition (from defineProps) */
  props?: Record<string, any>;
  /** Events (from defineEmits) */
  events?: string[];
}

/**
 * Generate Component() constructor wrapper
 */
export function generateComponentConstructor(options: ComponentGeneratorOptions): string {
  const {
    name,
    scriptCode,
    reactiveVars,
    templateDeps,
    props = {},
    events = [],
  } = options;

  // Filter reactive vars to only those used in template
  const boundVars = reactiveVars.filter(v =>
    templateDeps.length === 0 || templateDeps.includes(v)
  );

  // Generate data initialization
  const dataInit = boundVars.map(v => {
    return `    ${v}: typeof ${v} !== 'undefined' && ${v} && 'value' in ${v} ? ${v}.value : ${v}`;
  }).join(',\n');

  // Generate properties definition
  const propsDef = Object.entries(props).map(([key, def]) => {
    if (typeof def === 'string') {
      return `    ${key}: { type: ${def} }`;
    }
    return `    ${key}: ${JSON.stringify(def)}`;
  }).join(',\n');

  // Generate emit method
  const emitMethod = events.length > 0
    ? `
    $emit: function(event) {
      var args = Array.prototype.slice.call(arguments, 1);
      this.triggerEvent(event, args.length === 1 ? args[0] : args);
    }`
    : '';

  return `// Dualler Component: ${name}
// Auto-generated by Dualler Compiler
(function() {
  // === User script ===
  ${scriptCode}

  // === Component registration ===
  Component({
    data: {
${dataInit || '      // No reactive data'}
    },

    properties: {
${propsDef || '      // No props'}
    },

    methods: {${emitMethod}
    },

    lifetimes: {
      created: function() {
        if (typeof __dualler_onBeforeMount === 'function') __dualler_onBeforeMount();
      },
      attached: function() {
        if (typeof __dualler_onMounted === 'function') __dualler_onMounted();
      },
      ready: function() {
        if (typeof __dualler_onReady === 'function') __dualler_onReady();
      },
      detached: function() {
        if (typeof __dualler_onBeforeUnmount === 'function') __dualler_onBeforeUnmount();
        if (typeof __dualler_onUnmounted === 'function') __dualler_onUnmounted();
      }
    },

    pageLifetimes: {
      show: function() {
        if (typeof __dualler_onActivated === 'function') __dualler_onActivated();
      },
      hide: function() {
        if (typeof __dualler_onDeactivated === 'function') __dualler_onDeactivated();
      }
    }
  });
})();`;
}

/**
 * Extract props definition from defineProps() call
 */
export function extractProps(scriptContent: string): Record<string, any> {
  const props: Record<string, any> = {};

  // Match defineProps({ ... })
  const match = scriptContent.match(/defineProps\s*(?:<[^>]+>)?\s*\(\s*\{([\s\S]*?)\}\s*\)/);
  if (!match) return props;

  const propsBody = match[1];

  // Simple property extraction (handles most common cases)
  const propRegex = /(\w+)\s*:\s*\{([^}]+)\}/g;
  let propMatch;
  while ((propMatch = propRegex.exec(propsBody)) !== null) {
    const propName = propMatch[1];
    const propDef = propMatch[2];

    // Extract type
    const typeMatch = propDef.match(/type:\s*(\w+)/);
    const defaultMatch = propDef.match(/default:\s*([^,}]+)/);

    props[propName] = {
      type: typeMatch ? typeMatch[1] : 'Object',
      ...(defaultMatch ? { default: defaultMatch[1].trim() } : {}),
    };
  }

  return props;
}

/**
 * Extract emits from defineEmits() call
 */
export function extractEmits(scriptContent: string): string[] {
  const match = scriptContent.match(/defineEmits\s*\(\s*\[([^\]]*)\]\s*\)/);
  if (!match) return [];

  return match[1]
    .split(',')
    .map(e => e.trim().replace(/['"]/g, ''))
    .filter(Boolean);
}
