// Dualler App Entry
// appId: com.example.dualler-demo
// Generated by Dualler Compiler v2.0.0


import { onLaunch, onShow, onHide } from "dualler://runtime";

onLaunch(() => {
  console.log('App Launch');
});

onShow(() => {
  console.log('App Show');
});

onHide(() => {
  console.log('App Hide');
});