pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'org.jetbrains.kotlin.multiplatform' ||
                requested.id.id == 'org.jetbrains.kotlin.android' ||
                requested.id.id == 'org.jetbrains.kotlin.jvm') {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22")
            } else if (requested.id.id == 'org.jetbrains.kotlin.plugin.serialization') {
                useModule("org.jetbrains.kotlin:kotlin-serialization:1.9.22")
            } else if (requested.id.id.startsWith('com.android')) {
                useModule("com.android.tools.build:gradle:8.2.2")
            }
        }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "DuallerDemo"

// SDK modules
include ':platform-kmp'
project(':platform-kmp').projectDir = new File('../../packages/platform-kmp')

include ':core-kmp'
project(':core-kmp').projectDir = new File('../../packages/core-kmp')

include ':android'
project(':android').projectDir = new File('../../packages/android')

include ':app'
